led.plot(1, 0)
led.plot(3, 0)
led.plot(2, 1)
basic.forever(function () {
    led.toggle(0, 2)
    led.toggle(4, 2)
    led.toggle(1, 3)
    led.toggle(2, 3)
    led.toggle(3, 3)
    basic.pause(200)
})
